
#model-related https://github.com/clovaai/aasist/blob/a04c9863f63d44471dde8a6abcb3b082b07cd1d1/config/AASIST.conf
model:
  architecture: 'AASIST'
  nb_samp: 64600
  first_conv: 128
  filts: [70, [1, 32], [32, 32], [32, 64], [64, 64]]
  gat_dims: [64, 32]
  pool_ratios: [0.5, 0.7, 0.5, 0.5]
  temperatures: [2.0, 2.0, 100.0, 100.0]

